{% set name = "smartg" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/smartg-{{ version }}.tar.gz
  sha256: 8159ea03290cdf1a7a6db64a19848b73952320a9ed0b04b5a4edd236bac8c583

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }},<3.15
    - numpy >=2,<3
    - xarray
    - pandas
    - scipy
    - h5py
    - openpyxl
    - progressbar2
    - tqdm
    - matplotlib-base
    - python-dotenv
    - notebook
    - jupytext >=1.16,<2
    - ipywidgets
    - ipympl
    - pycuda
    - geoclide >=4.0.0,<5
    - luts
    - pytrunc >=2.1.0,<3
    - gatiab >=1.1.2,<2

test:
  imports:
    - smartg
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/hygeos/smartg
  summary: SMART-G (Speed-up Monte Carlo Advanced Radiative Transfer Code using GPU) is a radiative transfer code using a Monte-Carlo technique to simulate the propagation of the polarized light in the atmosphere and/or ocean, and using GPU acceleration.
  license: LicenseRef-HYGEOS-smartg
  license_url: https://github.com/hygeos/smartg/blob/master/LICENSE.TXT
  license_file:
    - LICENSE.TXT
    - LICENSE_RNG.TXT
  dev_url: https://github.com/hygeos/smartg

extra:
  recipe-maintainers:
    - musmoulana
