{% set name = "smartg" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smartg-{{ version }}.tar.gz
  sha256: 3302124f7fb4443a1265b9cd5ea806a5b53b874847ca73f0b2e1e44e83f17263

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - scipy
    - h5py
    - pyarrow
    - openpyxl
    - progressbar2
    - matplotlib
    - python-dotenv
    - notebook
    - ipywidgets
    - ipympl
    - pyhdf
    - pycuda
    - geoclide >=3
    - luts

test:
  imports:
    - smartg
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/hygeos/smartg
  summary: SMART-G (Speed-up Monte Carlo Advanced Radiative Transfer Code using GPU) is a radiative transfer code using a Monte-Carlo technique to simulate the propagation of the polarized light in the atmosphere and/or ocean, and using GPU acceleration.
  license: LicenseRef-HYGEOS-smartg
  license_url: https://github.com/hygeos/smartg/blob/master/LICENSE.TXT
  license_file:
    - LICENSE.TXT
    - LICENSE_RNG.TXT
  dev_url: https://github.com/hygeos/smartg

extra:
  recipe-maintainers:
    - Mustapha-hygeos
